### ISSUE TITLE
need shorter invitations

### ISSUE THREAD

**Issue by b1conrad** [Picolab/aries-cloudagent-pico#11]
Our connections invitation URLs are much too long. The generated QR Code is too large to be readable by some scanners (in particular the trinsic phone app).

**Comment by b1conrad** [comment]
We should be able to do this with the tag server of our Manifold instance

**Comment by b1conrad** [comment]
Have an [initial commit](https://github.com/Picolab/aries-cloudagent-pico/commit/8bb2e85ea531ce1ac5cb23164b3e77937b614515) which has an example for which the QR Code would look like this:

![sample](https://user-images.githubusercontent.com/19273926/111584767-eb1ddb00-8783-11eb-927f-4a300fb3e03d.png)

**Comment by b1conrad** [comment]
Remaining step is to incorporate the shortcut and its QR Code into the workflow. The challenge is that the invitation is currently produced with a query, and registering the URL and its shortcut requires an event.

**Comment by b1conrad** [comment]
A recent [commit](https://github.com/Picolab/aries-cloudagent-pico/commit/5f5d3002db0ce430a77090b78c15964ca5a1fb15) fixes this, by adding a new ruleset named (for conciseness) simply `s`.

If used, the shortener ruleset **MUST** be installed in a pico _before_ the `io.picolabs.aca.connections` ruleset, because it is used as the latter ruleset is being installed.

The changes surrounding this issue still need to be fixed for the v1 engine in the `NEXT` folder.

**Comment by windley** [comment]
How do you think that could be enforced or made simple?
